sudo: required
language: cpp
osx_image: xcode7.3
before_install:
 - brew update
 - brew install bison 
 - brew link --force bison
 - export SOUFFLECPP=`pwd`/wave/wave
compiler:
- clang
os:
 - osx
script:
 - sh ./bootstrap
 - ./configure
 - make 
 - make check
 - ./travis-debug-script.sh

